#!/bin/sh
### BEGIN INIT INFO
# Provides:		Tinker_boot
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Tinker_boot
# Description:		This service is used to start my applaction
### END INIT INFO

case "$1" in
    start)
	echo "start /home/linaro/init/myinit.sh"
	/home/linaro/init/myinit.sh
	;;
    stop)
	echo "stop function exe."
	;;
    *)
	echo "Usage: service Tinker_boot start|stop"
	exit 1
	;;
esac

exit 0
